name: ms3d
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda-gcc-specs=15.1.0=hc55bae6_2
  - ffmpeg=4.3
  - freetype=2.13.3=h4a9f257_0
  - gcc=15.1.0=h33e79ad_2
  - gcc_impl_linux-64=15.1.0=h4393ad2_2
  - glew=2.1.0=h9c3ff4c_2
  - glfw=3.4=hd590300_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.2=h59595ed_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=15.1.0=h4c094af_102
  - libgcc-ng=15.1.0=h69a702a_2
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpng=1.6.39=h5eee18b_0
  - libsanitizer=15.1.0=h97b714f_2
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.0=h7b32b05_1
  - pillow=11.1.0=py310hac6e08b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.3.0=py310h06a4308_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - ccimport==0.4.4
      - cffi==1.17.1
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7
      - cumm-cu113==0.4.11
      - dash==3.0.4
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - easydict==1.13
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fire==0.7.0
      - flask==3.0.3
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ifaddr==0.2.0
      - imageio==2.37.0
      - importlib-metadata==6.6.0
      - ipykernel==6.29.5
      - ipython==8.35.0
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - kiss-icp==1.1.0
      - lark==1.2.2
      - laspy==2.5.4
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - lz4==4.4.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - more-itertools==10.7.0
      - motmetrics==1.4.0
      - narwhals==1.36.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - notebook==7.4.1
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - nuscenes-devkit==1.0.5
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - ouster-sdk==0.14.0
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pccm==0.4.16
      - pexpect==4.9.0
      - pip
      - platformdirs==4.3.7
      - plotly==6.0.1
      - plyfile==1.1
      - point-cloud-utils==0.34.0
      - polyscope==2.4.0
      - portalocker==3.1.1
      - prettytable==3.16.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - protobuf==6.31.0rc1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==2.14.0.dev1
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pygments==2.19.1
      - pyntcloud==0.3.1
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rosbags==0.9.23
      - rpds-py==0.24.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - send2trash==1.8.3
      - setuptools==80.7.1
      - sharedarray==3.2.4
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.7
      - spconv-cu113==2.3.6
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - termcolor==3.0.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.6.9
      - typer==0.15.4
      - types-python-dateutil==2.9.0.20241206
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - xmltodict==0.14.2
      - zeroconf==0.147.0
      - zipp==3.21.0
      - zstandard==0.23.0
prefix: /home/ys/anaconda3/envs/ms3d
